### ISSUE TITLE
Options menu doesn't work in Lollypop (5.1)

### ISSUE THREAD

**Issue by slobodsky** [ditek/MidiSheetMusic-Android#1] opened 2019-03-24 09:44 UTC
When I press the "hamburger" button on my x86 Android 5.1 tablet or in the emulator with the same OS, nothing happens. Android 7 in the emulator works well.

**Comment by ditek** [comment] 2019-03-24 12:35
Thanks for reporting.
I'm planning to change the way the options menu works and convert it to a side sliding panel. This will probably fix the issue.
This, among other changes, will come during the coming few weeks.

**Comment by slobodsky** [comment] 2019-03-25 12:25
I've figured out a quick fix for this problem. Just added the ActionBar for that activity (it's still invisible while int the Fullscreen mode). See my fork for details.

**Comment by ditek** [comment] 2019-07-04 09:29
I added a side drawer, which should fix the issue. Sorry it took a long time to fix.
I couldn't get my emulator to work properly on Lollypop. If you have access to a device maybe you can confirm if it works.

**Comment by ditek** [comment] 2019-08-20 21:08
Closing this for now. Please comment if the issue is not solved.

**Closed as completed by ditek** 2019-08-20 21:08 UTC
Labels: bug
